use DAQ
create table VARIABLE_DAQ (ID int primary key identity(1,1),DATE_TIME varchar(50), FREQUENCY_RICH varchar(20), CURRENT_RICH varchar(20),
FREQUENCY_DELTA varchar(20), CURRENT_DELTA VARCHAR(20), TYPE_OF_PRODUCT VARCHAR(20),
QUALITY_PRODUCT VARCHAR(20), ERROR_PRODUCT VARCHAR(20), CHIEU_DAI_SPLOI VARCHAR(20), DUONG_KINH_ONG VARCHAR(20),
BE_DAY VARCHAR(20), CHIEU_DAI_CAT VARCHAR(20),
MOTOR_SPEED VARCHAR(20), DC_VOLT VARCHAR(20), DC_AMPE VARCHAR(20), 
HEATER_9 VARCHAR(20), 
HEATER_1_3 VARCHAR(20),HEATER_2 VARCHAR(20), HEATER_8_10 VARCHAR(20),ZONE_1B_2B VARCHAR(20),ZONE_3B_4B VARCHAR(20), 
ZONE_1A_2A VARCHAR(20),ZONE_3A_4A VARCHAR(20),LOSAY_CAO_TREN VARCHAR(20),LOSAY_CAO_DUOI VARCHAR(20),LOSAY_THAP_TREN VARCHAR(20),
LOSAY_THAP_DUOI VARCHAR(20) )
